// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package myjson

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1a3d1914DecodeGithubComNxthxnXUrlshortenerInternalMyjson(in *jlexer.Lexer, out *ApiShortenResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "result":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Result = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1a3d1914EncodeGithubComNxthxnXUrlshortenerInternalMyjson(out *jwriter.Writer, in ApiShortenResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		out.String(string(in.Result))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ApiShortenResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1a3d1914EncodeGithubComNxthxnXUrlshortenerInternalMyjson(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ApiShortenResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1a3d1914EncodeGithubComNxthxnXUrlshortenerInternalMyjson(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ApiShortenResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1a3d1914DecodeGithubComNxthxnXUrlshortenerInternalMyjson(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ApiShortenResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1a3d1914DecodeGithubComNxthxnXUrlshortenerInternalMyjson(l, v)
}
func easyjson1a3d1914DecodeGithubComNxthxnXUrlshortenerInternalMyjson1(in *jlexer.Lexer, out *ApiShortenRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1a3d1914EncodeGithubComNxthxnXUrlshortenerInternalMyjson1(out *jwriter.Writer, in ApiShortenRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ApiShortenRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1a3d1914EncodeGithubComNxthxnXUrlshortenerInternalMyjson1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ApiShortenRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1a3d1914EncodeGithubComNxthxnXUrlshortenerInternalMyjson1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ApiShortenRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1a3d1914DecodeGithubComNxthxnXUrlshortenerInternalMyjson1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ApiShortenRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1a3d1914DecodeGithubComNxthxnXUrlshortenerInternalMyjson1(l, v)
}
